Disable auto-discovery for setuptools
With setuptools release 61.0.0 ansible-role-thales-hsm's package build
command (python3 setup.py sdist bdist_wheel) started to fail:

error: Multiple top-level packages discovered in a flat-layout:
['files', 'defaults', 'handlers', 'templates', 'releasenotes'].

This bug is mentioned in setuptools issue 3197 [1], and the suggested
workaround is to disable auto-discovery by adding 'py_modules=[]' in
setup.py.

ansible-lint also released a new version (6.0.0), which has new rules
that blocks the gate. As a workaround, this patch caps ansible-lint
version <6.0.0 to unblock the gate.

[1] https://github.com/pypa/setuptools/issues/3197

Change-Id: Idb765d09f9498bc13f952c055026e29a46cab8d3
(cherry picked from commit 49970b3ceb66a87c3d3e95ac77eda9ffd6b5a0f1)
(cherry picked from commit 3f88a20fe91e8e3a8f870a5f9a95951a3a91d7ef)